
import java.awt.Cursor;
import javax.swing.WindowConstants;

public class first extends javax.swing.JFrame {
    private MySoundEffect themeSound;
    private boolean moved = false;
    private boolean clicked = false;
    instruction     instr;
    creditpage      crd;
    trophy          trp;
    public first() {
        setTitle("Catch Me");
        setBounds(0,0,2000,1000);
        setVisible(true);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        themeSound = new MySoundEffect("C:\\Users\\My Documents\\Desktop\\project\\project_sound\\toystory.wav");
        themeSound.playLoop();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play = new javax.swing.JButton();
        credit = new javax.swing.JButton();
        rank = new javax.swing.JButton();
        howto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play_but1.png"))); // NOI18N
        play.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                playMouseMoved(evt);
            }
        });
        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playMouseClicked(evt);
            }
        });
        getContentPane().add(play);
        play.setBounds(740, 520, 480, 260);

        credit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/credit_2.png"))); // NOI18N
        credit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditMouseClicked(evt);
            }
        });
        getContentPane().add(credit);
        credit.setBounds(1770, 750, 210, 210);

        rank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trophy_but1.png"))); // NOI18N
        rank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rankMouseClicked(evt);
            }
        });
        getContentPane().add(rank);
        rank.setBounds(1550, 750, 220, 210);

        howto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Question_mark_but1.png"))); // NOI18N
        howto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                howtoMouseClicked(evt);
            }
        });
        getContentPane().add(howto);
        howto.setBounds(1310, 750, 240, 210);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1st_page.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 2000, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseMoved

    }//GEN-LAST:event_playMouseMoved

    private void playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseClicked
        if(evt.getClickCount()==1){
           play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play_but2.png")));
           
        }
    }//GEN-LAST:event_playMouseClicked

    private void howtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howtoMouseClicked
        if(evt.getClickCount()==1){
           howto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Question_mark_but2.png")));
           instr = new instruction();
           instr.setVisible(true);
        }
    }//GEN-LAST:event_howtoMouseClicked

    private void rankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankMouseClicked
        if(evt.getClickCount()==1){
           rank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trophy_but2.png")));
           trp = new trophy();
           trp.setVisible(true);
        }
    }//GEN-LAST:event_rankMouseClicked

    private void creditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditMouseClicked
        if(evt.getClickCount()==1){
           credit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/credit_1.png")));
           crd = new creditpage();
           crd.setVisible(true);
        }
    }//GEN-LAST:event_creditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new first().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton credit;
    private javax.swing.JButton howto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton play;
    private javax.swing.JButton rank;
    // End of variables declaration//GEN-END:variables
}
class MySoundEffect{
    private java.applet.AudioClip audio;
    public MySoundEffect(String filename){
        try{
            java.io.File file = new java.io.File(filename);
            audio = java.applet.Applet.newAudioClip(file.toURL());
        }catch(Exception e){
            e.printStackTrace();
        } 
    }
    public void playOnce()  { audio.play(); }
    public void playLoop()  { audio.loop(); }
    public void playstop()  { audio.stop(); }

};
