/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proparaproj3;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author po-pe
 */
public class level_chose extends javax.swing.JFrame {
private boolean moved = false;
    private boolean clicked = false;
    instruction     instr;
    /**
     * Creates new form level_chose
     */
    public level_chose() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medbox = new javax.swing.JButton();
        insbox = new javax.swing.JButton();
        easybox = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        medbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proparaproj3/med_but.PNG"))); // NOI18N
        medbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medboxMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                medboxMouseReleased(evt);
            }
        });
        medbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medboxActionPerformed(evt);
            }
        });
        getContentPane().add(medbox);
        medbox.setBounds(920, 810, 200, 100);

        insbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proparaproj3/ins_but.PNG"))); // NOI18N
        insbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insboxMouseClicked(evt);
            }
        });
        insbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insboxActionPerformed(evt);
            }
        });
        getContentPane().add(insbox);
        insbox.setBounds(1600, 810, 200, 100);

        easybox.setIcon(new javax.swing.ImageIcon("C:\\Users\\po-pe\\Desktop\\propara_project3\\easy_but.PNG")); // NOI18N
        easybox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                easyboxMouseMoved(evt);
            }
        });
        easybox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyboxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                easyboxMouseEntered(evt);
            }
        });
        easybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyboxActionPerformed(evt);
            }
        });
        getContentPane().add(easybox);
        easybox.setBounds(240, 790, 200, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\po-pe\\Desktop\\propara_project3\\level_wall.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 2000, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medboxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_medboxActionPerformed

    private void insboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insboxActionPerformed

    private void medboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medboxMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
           medbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("go_but.png")));
           instr = new instruction();
           instr.setVisible(true);
        }
    }//GEN-LAST:event_medboxMouseClicked

    private void insboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insboxMouseClicked
        if(evt.getClickCount()==1){
           insbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("go_but.png")));
           instr = new instruction();
           instr.setVisible(true);
        }
    }//GEN-LAST:event_insboxMouseClicked

    private void medboxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medboxMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_medboxMouseReleased

    private void easyboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easyboxActionPerformed

    private void easyboxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyboxMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_easyboxMouseEntered

    private void easyboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyboxMouseClicked
        if(evt.getClickCount()==1){
           easybox.setIcon(new javax.swing.ImageIcon(getClass().getResource("go_but.png")));
           instr = new instruction();
           instr.setVisible(true);
        }
    }//GEN-LAST:event_easyboxMouseClicked

    private void easyboxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyboxMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_easyboxMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(level_chose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(level_chose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(level_chose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(level_chose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new level_chose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easybox;
    private javax.swing.JButton insbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton medbox;
    // End of variables declaration//GEN-END:variables
}
