/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proparaproj3;

/**
 *
 * @author po-pe
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    private boolean moved = false;
    private boolean clicked = false;
    instruction     instr;
    
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group1 = new javax.swing.ButtonGroup();
        dol = new javax.swing.JRadioButton();
        cat = new javax.swing.JRadioButton();
        jas = new javax.swing.JRadioButton();
        ari = new javax.swing.JRadioButton();
        chip = new javax.swing.JRadioButton();
        tan = new javax.swing.JRadioButton();
        pin = new javax.swing.JRadioButton();
        jud = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        group1.add(dol);
        dol.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        dol.setForeground(new java.awt.Color(255, 204, 51));
        dol.setText("\"Donald duck\"");
        dol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proparaproj3/reddot.png"))); // NOI18N
        dol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dolMouseClicked(evt);
            }
        });
        dol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dolActionPerformed(evt);
            }
        });
        getContentPane().add(dol);
        dol.setBounds(1560, 350, 370, 90);

        group1.add(cat);
        cat.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        cat.setForeground(new java.awt.Color(255, 0, 204));
        cat.setText("\"Cheshire\" ");
        cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proparaproj3/reddot.png"))); // NOI18N
        cat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catMouseClicked(evt);
            }
        });
        cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catActionPerformed(evt);
            }
        });
        getContentPane().add(cat);
        cat.setBounds(60, 330, 320, 120);

        group1.add(jas);
        jas.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        jas.setText("\"Jasmine\" ");
        jas.setSize(100,100);
        jas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proparaproj3/reddot.png"))); // NOI18N
        jas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jasMouseClicked(evt);
            }
        });
        jas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jasActionPerformed(evt);
            }
        });
        getContentPane().add(jas);
        jas.setBounds(600, 350, 360, 80);

        group1.add(ari);
        ari.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        ari.setForeground(new java.awt.Color(0, 204, 204));
        ari.setText("\"Ariel\" ");
        ari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proparaproj3/reddot.png"))); // NOI18N
        ari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ariMouseClicked(evt);
            }
        });
        ari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ariActionPerformed(evt);
            }
        });
        getContentPane().add(ari);
        ari.setBounds(1140, 340, 250, 100);

        group1.add(chip);
        chip.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        chip.setForeground(new java.awt.Color(255, 102, 51));
        chip.setText("\"Chip Dale\"");
        chip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proparaproj3/reddot.png"))); // NOI18N
        chip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chipMouseClicked(evt);
            }
        });
        chip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chipActionPerformed(evt);
            }
        });
        getContentPane().add(chip);
        chip.setBounds(40, 860, 360, 90);

        group1.add(tan);
        tan.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        tan.setForeground(new java.awt.Color(0, 102, 102));
        tan.setText("\"Tazans\"");
        tan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proparaproj3/reddot.png"))); // NOI18N
        tan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanMouseClicked(evt);
            }
        });
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });
        getContentPane().add(tan);
        tan.setBounds(1650, 840, 300, 90);

        group1.add(pin);
        pin.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        pin.setForeground(new java.awt.Color(153, 102, 0));
        pin.setText("\"Pinochio");
        pin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proparaproj3/reddot.png"))); // NOI18N
        pin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pinMouseClicked(evt);
            }
        });
        pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinActionPerformed(evt);
            }
        });
        getContentPane().add(pin);
        pin.setBounds(600, 860, 280, 70);

        group1.add(jud);
        jud.setFont(new java.awt.Font("Pahnto", 1, 60)); // NOI18N
        jud.setForeground(new java.awt.Color(51, 102, 255));
        jud.setText("\"Judy\"");
        jud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proparaproj3/reddot.png"))); // NOI18N
        jud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                judMouseClicked(evt);
            }
        });
        jud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judActionPerformed(evt);
            }
        });
        getContentPane().add(jud);
        jud.setBounds(1220, 830, 200, 130);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proparaproj3/tazan.PNG"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1600, 490, 340, 280);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\po-pe\\Desktop\\propara_project3\\judy.PNG")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1130, 530, 260, 220);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\po-pe\\Desktop\\propara_project3\\char_pinoc.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(620, 480, 230, 320);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proparaproj3/char_chipdale.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 520, 330, 280);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\po-pe\\Desktop\\propara_project3\\char_donaldduck.PNG")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1620, 0, 310, 340);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\po-pe\\Desktop\\propara_project3\\char_jusmine.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, -10, 270, 370);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\po-pe\\Desktop\\propara_project3\\char_arial.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1160, 10, 390, 320);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proparaproj3/char_cheshire.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 80, 380, 210);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\po-pe\\Desktop\\propara_project3\\char_selected_wall.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1990, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dolActionPerformed

    private void catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catActionPerformed

    private void jasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jasActionPerformed

    private void ariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ariActionPerformed

    private void chipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chipActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanActionPerformed

    private void pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinActionPerformed

    private void judActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judActionPerformed

    private void catMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catMouseClicked
        if(evt.getClickCount()==1){
            cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("dot.png")));
           instr = new instruction();
           instr.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_catMouseClicked

    private void jasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jasMouseClicked
     if(evt.getClickCount()==1){
            jas.setIcon(new javax.swing.ImageIcon(getClass().getResource("dot.png")));
           instr = new instruction();
           instr.setVisible(true);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jasMouseClicked

    private void ariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ariMouseClicked
if(evt.getClickCount()==1){
            ari.setIcon(new javax.swing.ImageIcon(getClass().getResource("b_dot.png")));
           instr = new instruction();
           instr.setVisible(true);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_ariMouseClicked

    private void dolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dolMouseClicked
if(evt.getClickCount()==1){
            dol.setIcon(new javax.swing.ImageIcon(getClass().getResource("go_but.png")));
           instr = new instruction();
           instr.setVisible(true);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_dolMouseClicked

    private void chipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chipMouseClicked
if(evt.getClickCount()==1){
            chip.setIcon(new javax.swing.ImageIcon(getClass().getResource("reddot_1.png")));
           instr = new instruction();
           instr.setVisible(true);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_chipMouseClicked

    private void pinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinMouseClicked
if(evt.getClickCount()==1){
            pin.setIcon(new javax.swing.ImageIcon(getClass().getResource("b_dot.png")));
           instr = new instruction();
           instr.setVisible(true);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_pinMouseClicked

    private void judMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_judMouseClicked
if(evt.getClickCount()==1){
            jud.setIcon(new javax.swing.ImageIcon(getClass().getResource("b_dot.png")));
           instr = new instruction();
           instr.setVisible(true);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_judMouseClicked

    private void tanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
           tan.setIcon(new javax.swing.ImageIcon(getClass().getResource("b_dot.png")));
           instr = new instruction();
           instr.setVisible(true);
        }  
    }//GEN-LAST:event_tanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ari;
    private javax.swing.JRadioButton cat;
    private javax.swing.JRadioButton chip;
    private javax.swing.JRadioButton dol;
    private javax.swing.ButtonGroup group1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jas;
    private javax.swing.JRadioButton jud;
    private javax.swing.JRadioButton pin;
    private javax.swing.JRadioButton tan;
    // End of variables declaration//GEN-END:variables
}
