
import java.awt.Image;
import javax.swing.ImageIcon;

public class wallpaper extends javax.swing.JFrame {

    MyImageIcon     aladdin,mermiad,mulan,tangled;
    public wallpaper() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo = new javax.swing.JComboBox<>();
        wallpp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        combo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        combo.setMaximumRowCount(4);
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aladdin", "Mulan", "Tangled", "Arial" }));
        combo.setMinimumSize(new java.awt.Dimension(100, 60));
        combo.setPreferredSize(new java.awt.Dimension(100, 60));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo);
        combo.setBounds(1590, 250, 220, 110);

        wallpp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selectWall.png"))); // NOI18N
        getContentPane().add(wallpp);
        wallpp.setBounds(0, 0, 2040, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
            if(combo.getSelectedIndex()==0){
                aladdin = new MyImageIcon("C:\\Users\\My Documents\\Desktop\\project\\project_pic\\wallpaper\\aladin_wall.png");
                wallpp.setIcon(aladdin);
            }else if(combo.getSelectedIndex()==1){
                mulan = new MyImageIcon("C:\\Users\\My Documents\\Desktop\\project\\project_pic\\wallpaper\\mulan_wall.png");
                wallpp.setIcon(mulan);
            }else if(combo.getSelectedIndex()==2){
                tangled = new MyImageIcon("C:\\Users\\My Documents\\Desktop\\project\\project_pic\\wallpaper\\tangled_wall.png");
                wallpp.setIcon(tangled);
            }else if(combo.getSelectedIndex()==3){
                mermiad = new MyImageIcon("C:\\Users\\My Documents\\Desktop\\project\\project_pic\\wallpaper\\arial_wall.png");
                wallpp.setIcon(mermiad);
            }
        
        
    }//GEN-LAST:event_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wallpaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wallpaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wallpaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wallpaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wallpaper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel wallpp;
    // End of variables declaration//GEN-END:variables
}
class MyImageIcon extends ImageIcon
{
	public MyImageIcon(String fname)  { super(fname); }
	public MyImageIcon(Image image)   { super(image); }

	public MyImageIcon resize(int width, int height)
	{
		Image oldimg = this.getImage();
		Image newimg = oldimg.getScaledInstance(width, height,java.awt.Image.SCALE_SMOOTH);
		return new MyImageIcon(newimg);
	}
};
